/*
 * This file is generated by jOOQ.
 */
package com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.pojos;


import com.gramant.dentsuCampaignCalculator.domain.CalculationMethod;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Campaign implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID              id;
    private String            name;
    private UUID              productCode;
    private CalculationMethod calculation;
    private Integer           budget;
    private Integer           weeks;

    public Campaign() {}

    public Campaign(Campaign value) {
        this.id = value.id;
        this.name = value.name;
        this.productCode = value.productCode;
        this.calculation = value.calculation;
        this.budget = value.budget;
        this.weeks = value.weeks;
    }

    public Campaign(
        UUID              id,
        String            name,
        UUID              productCode,
        CalculationMethod calculation,
        Integer           budget,
        Integer           weeks
    ) {
        this.id = id;
        this.name = name;
        this.productCode = productCode;
        this.calculation = calculation;
        this.budget = budget;
        this.weeks = weeks;
    }

    /**
     * Getter for <code>public.campaign.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.campaign.id</code>.
     */
    public Campaign setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.campaign.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.campaign.name</code>.
     */
    public Campaign setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.campaign.product_code</code>.
     */
    public UUID getProductCode() {
        return this.productCode;
    }

    /**
     * Setter for <code>public.campaign.product_code</code>.
     */
    public Campaign setProductCode(UUID productCode) {
        this.productCode = productCode;
        return this;
    }

    /**
     * Getter for <code>public.campaign.calculation</code>.
     */
    public CalculationMethod getCalculation() {
        return this.calculation;
    }

    /**
     * Setter for <code>public.campaign.calculation</code>.
     */
    public Campaign setCalculation(CalculationMethod calculation) {
        this.calculation = calculation;
        return this;
    }

    /**
     * Getter for <code>public.campaign.budget</code>.
     */
    public Integer getBudget() {
        return this.budget;
    }

    /**
     * Setter for <code>public.campaign.budget</code>.
     */
    public Campaign setBudget(Integer budget) {
        this.budget = budget;
        return this;
    }

    /**
     * Getter for <code>public.campaign.weeks</code>.
     */
    public Integer getWeeks() {
        return this.weeks;
    }

    /**
     * Setter for <code>public.campaign.weeks</code>.
     */
    public Campaign setWeeks(Integer weeks) {
        this.weeks = weeks;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Campaign other = (Campaign) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (productCode == null) {
            if (other.productCode != null)
                return false;
        }
        else if (!productCode.equals(other.productCode))
            return false;
        if (calculation == null) {
            if (other.calculation != null)
                return false;
        }
        else if (!calculation.equals(other.calculation))
            return false;
        if (budget == null) {
            if (other.budget != null)
                return false;
        }
        else if (!budget.equals(other.budget))
            return false;
        if (weeks == null) {
            if (other.weeks != null)
                return false;
        }
        else if (!weeks.equals(other.weeks))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.productCode == null) ? 0 : this.productCode.hashCode());
        result = prime * result + ((this.calculation == null) ? 0 : this.calculation.hashCode());
        result = prime * result + ((this.budget == null) ? 0 : this.budget.hashCode());
        result = prime * result + ((this.weeks == null) ? 0 : this.weeks.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Campaign (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(productCode);
        sb.append(", ").append(calculation);
        sb.append(", ").append(budget);
        sb.append(", ").append(weeks);

        sb.append(")");
        return sb.toString();
    }
}
