/*
 * This file is generated by jOOQ.
 */
package com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID   code;
    private String name;

    public Product() {}

    public Product(Product value) {
        this.code = value.code;
        this.name = value.name;
    }

    public Product(
        UUID   code,
        String name
    ) {
        this.code = code;
        this.name = name;
    }

    /**
     * Getter for <code>public.product.code</code>.
     */
    public UUID getCode() {
        return this.code;
    }

    /**
     * Setter for <code>public.product.code</code>.
     */
    public Product setCode(UUID code) {
        this.code = code;
        return this;
    }

    /**
     * Getter for <code>public.product.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.product.name</code>.
     */
    public Product setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Product other = (Product) obj;
        if (code == null) {
            if (other.code != null)
                return false;
        }
        else if (!code.equals(other.code))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(code);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
