/*
 * This file is generated by jOOQ.
 */
package com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data;


import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.CalculationModal;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.Campaign;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.Product;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.records.CalculationModalRecord;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.records.CampaignRecord;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.records.ProductRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CalculationModalRecord> CALCULATION_MODAL_PKEY = Internal.createUniqueKey(CalculationModal.CALCULATION_MODAL, DSL.name("calculation_modal_pkey"), new TableField[] { CalculationModal.CALCULATION_MODAL.DATE_START, CalculationModal.CALCULATION_MODAL.DATE_END, CalculationModal.CALCULATION_MODAL.PRODUCT, CalculationModal.CALCULATION_MODAL.CAMPAIGN, CalculationModal.CALCULATION_MODAL.CRM, CalculationModal.CALCULATION_MODAL.CHANNEL, CalculationModal.CALCULATION_MODAL.PLAYGROUND, CalculationModal.CALCULATION_MODAL.FORMAT, CalculationModal.CALCULATION_MODAL.VERSION }, true);
    public static final UniqueKey<CampaignRecord> PK_CAMPAIGN_ID = Internal.createUniqueKey(Campaign.CAMPAIGN, DSL.name("pk_campaign_id"), new TableField[] { Campaign.CAMPAIGN.ID }, true);
    public static final UniqueKey<CampaignRecord> UQ_CAMPAIGN_NAME = Internal.createUniqueKey(Campaign.CAMPAIGN, DSL.name("uq_campaign_name"), new TableField[] { Campaign.CAMPAIGN.NAME }, true);
    public static final UniqueKey<ProductRecord> PK_CODE = Internal.createUniqueKey(Product.PRODUCT, DSL.name("pk_code"), new TableField[] { Product.PRODUCT.CODE }, true);
    public static final UniqueKey<ProductRecord> UQ_PRODUCT_NAME = Internal.createUniqueKey(Product.PRODUCT, DSL.name("uq_product_name"), new TableField[] { Product.PRODUCT.NAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CampaignRecord, ProductRecord> CAMPAIGN__CAMPAIGN_PRODUCT_CODE_FKEY = Internal.createForeignKey(Campaign.CAMPAIGN, DSL.name("campaign_product_code_fkey"), new TableField[] { Campaign.CAMPAIGN.PRODUCT_CODE }, Keys.PK_CODE, new TableField[] { Product.PRODUCT.CODE }, true);
}
