/*
 * This file is generated by jOOQ.
 */
package com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data;


import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.CalculationModal;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.Campaign;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.Product;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.calculation_modal</code>.
     */
    public final CalculationModal CALCULATION_MODAL = CalculationModal.CALCULATION_MODAL;

    /**
     * The table <code>public.campaign</code>.
     */
    public final Campaign CAMPAIGN = Campaign.CAMPAIGN;

    /**
     * The table <code>public.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            CalculationModal.CALCULATION_MODAL,
            Campaign.CAMPAIGN,
            Product.PRODUCT);
    }
}
