/*
 * This file is generated by jOOQ.
 */
package com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data;


import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.CalculationModal;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.Campaign;
import com.gramant.dentsuCampaignCalculator.adapters.dbdomain.data.tables.Product;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.calculation_modal</code>.
     */
    public static final CalculationModal CALCULATION_MODAL = CalculationModal.CALCULATION_MODAL;

    /**
     * The table <code>public.campaign</code>.
     */
    public static final Campaign CAMPAIGN = Campaign.CAMPAIGN;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;
}
